# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Easywaldo's 블로그
email: easywaldoji@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  도전을 즐기고 앞으로 나아가는 개발자의 블로그입니다.
  새로운 기술을 배우고 경험을 공유합니다.
baseurl: "/go-forward" # the subpath of your site, e.g. /blog
url: "https://easywaldo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: easywaldo@gmail.com

# Build settings
remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Minimal Mistakes theme settings
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "Easywaldo"
  bio: "도전을 즐기고 앞으로 나아가는 개발자"
  location: "South Korea"
  email: "easywaldoji@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/easywaldo"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/easywaldo"

# Navigation
header_pages:
  - tech.md
  - daily.md
  - about.md

# Reading Files
include:
  - .htaccess
  - _pages

# Exclude
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      classes: wide
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

# Collections
collections:
  tech:
    output: true
    permalink: /:collection/:name/
  daily:
    output: true
    permalink: /:collection/:name/

# Disqus Comments
disqus:
  shortname: your-disqus-shortname

# Category descriptions
category_descriptions:
  tech: "기술 관련 포스트"
  daily: "일상 이야기"
  about: "내 소개"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
